version: "2"

services:

  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS : 0
      FORWARDLOGS: 0
      SAMPLEDATA : 0
    ports:
      - 2181:2181                     #zookeeper
      - 3030:3030                     #Landoop UI
      - 8081-8083:8081-8083           #REST proxy, Schema Registry, kafka-consumer
      - 9581-9585:9581-9585           #JMX Broker
      - 9092:9092                     #kafka Broker
